document.writeln("<ul>");
document.writeln("<li>");
document.writeln("<div class=\'left\' onclick=\' shangFw()\'>");
document.writeln("	<i></i>");
document.writeln("	<p>商标服务<span>TRADEMARK</span></p>");
document.writeln("	<b class=\'jiant\'></b>");
document.writeln("</div>");
document.writeln("<div class=\'childMenu\'>");
document.writeln("	<div class=\'div_asd\'> ");
document.writeln("		<div class=\'ZheShiK\'>");
document.writeln("			<div class=\'liangge_sd\'> ");
document.writeln("				<h3 class=\'biaot\'>商标注册</h3>");
document.writeln("				<ul>");
document.writeln("					<li class=\'hot\'><a href=\'#\'>自助注册</a></li>");
document.writeln("					<li><a href=\'#\'>极速注册</a></li>");
document.writeln("					<li><a href=\'#\'>保值注册</a></li>");
document.writeln("					<li><a href=\'#\'>风险代理</a></li>");
document.writeln("					<li><a href=\'#\'>商标查询</a></li>");
document.writeln("					<li><a href=\'#\'>商标分类表</a></li>");
document.writeln("					<li class=\'color_hot hot\'><a href=\'#\'>品牌定制</a></li>");
document.writeln("					<li class=\'color_hot\'><a href=\'#\'>品牌升级</a></li>");
document.writeln("				</ul> ");
document.writeln("			</div>");
document.writeln("			<div class=\'liangge_sd chang\'> ");
document.writeln("				<h3 class=\'biaot biaot1\'>商标维护</h3>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\'#\'>商标变更</a></li>");
document.writeln("					<li><a href=\'#\'>商标转让</a></li>");
document.writeln("					<li><a href=\'#\'>商标补证</a></li>");
document.writeln("					<li><a href=\'#\'>商标续展</a></li>");
document.writeln("					<li><a href=\'#\'>商标更正</a></li>");
document.writeln("					<li><a href=\'#\'>商标注销</a></li>");
document.writeln("					<li><a href=\'#\'>撤三举证</a></li>");
document.writeln("					<li><a href=\'#\'>撤三复审</a></li>");
document.writeln("					<li><a href=\'#\'>许可合同备案</a></li>");
document.writeln("					<li><a href=\'#\'>商标质押申请</a></li>");
document.writeln("					<li><a href=\'#\'>无效宣告答辩</a></li>");
document.writeln("					<li><a href=\'#\'>中国驰名商标认定</a></li>");
document.writeln("					<li><a href=\'#\'>商标管家</a></li>");
document.writeln("				</ul> ");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		<div class=\'LiangGe_FD\'></div>");
document.writeln("	</div>");
document.writeln("	<div class=\'div_asd\'> ");
document.writeln("		<div class=\'ZheShiK\'>");
document.writeln("			<div class=\'liangge_sd\'> ");
document.writeln("				<h3 class=\'biaot shangb\'>商标确权</h3>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\'#\'>驳回复审（普通版）</a></li>");
document.writeln("					<li><a href=\'#\'>驳回复审（保值版）</a></li>");
document.writeln("					<li><a href=\'#\'>驳回复审（担保版）</a></li>");
document.writeln("					<li><a href=\'#\'>异议申请</a></li>");
document.writeln("					<li><a href=\'#\'>异议答辩</a></li>");
document.writeln("					<li><a href=\'#\'>无效宣告申请</a></li>");
document.writeln("					<li><a href=\'#\'>撤销三年不使用</a></li> ");
document.writeln("				</ul> ");
document.writeln("			</div>");
document.writeln("			<div class=\'liangge_sd\'> ");
document.writeln("				<h3 class=\'biaot biaot1\'>特殊商标</h3>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\'#\'>证明商标</a></li>");
document.writeln("					<li><a href=\'#\'>集体商标</a></li>");
document.writeln("					<li><a href=\'#\'>地理标志证明商标</a></li>");
document.writeln("					<li><a href=\'#\'>地理标志集体商标</a></li> ");
document.writeln("				</ul> ");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		<div class=\'LiangGe_FD\'></div>");
document.writeln("	</div>");
document.writeln("	<div class=\'div_asd\'> ");
document.writeln("		<div class=\'ZheShiK\'>");
document.writeln("			<div class=\'\'> ");
document.writeln("				<h3 class=\'biaot guoji\'>国际商标注册</h3>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\'#\'>驳回复审（普通版）</a></li>");
document.writeln("					<li><a href=\'#\'>驳回复审（保值版）</a></li>");
document.writeln("					<li><a href=\'#\'>驳回复审（担保版）</a></li>");
document.writeln("					<li><a href=\'#\'>异议申请</a></li>");
document.writeln("					<li><a href=\'#\'>异议答辩</a></li>");
document.writeln("					<li><a href=\'#\'>无效宣告申请</a></li>");
document.writeln("					<li><a href=\'#\'>撤销三年不使用</a></li> ");
document.writeln("				</ul> ");
document.writeln("			</div> ");
document.writeln("		</div>");
document.writeln("		<div class=\'LiangGe_FD\'></div>");
document.writeln("	</div>");
document.writeln("	<div class=\'div_asd\'> ");
document.writeln("		<div class=\'ZheShiK\'>");
document.writeln("			<div class=\'\'> ");
document.writeln("				<h3 class=\'biaot jiaoyi\'>商标交易</h3>");
document.writeln("				<ul>");
document.writeln("					<li class=\'hot\'><a href=\'#\'>驳回复审（普通版）</a></li>");
document.writeln("					<li><a href=\'#\'>驳回复审（保值版）</a></li>");
document.writeln("					<li><a href=\'#\'>驳回复审（担保版）</a></li>");
document.writeln("					<li><a href=\'#\'>异议申请</a></li>");
document.writeln("					<li><a href=\'#\'>异议答辩</a></li>");
document.writeln("					<li class=\'color_hot\'><a href=\'#\'>无效宣告申请</a></li>");
document.writeln("					<li class=\'color_hot\'><a href=\'#\'>撤销三年不使用</a></li> ");
document.writeln("				</ul> ");
document.writeln("			</div> ");
document.writeln("		</div>");
document.writeln("		<!-- <div class=\'LiangGe_FD\'></div> -->");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("</li>");
document.writeln("<li class=\'nisd_w\'>");
document.writeln("<div class=\'left\' onclick=\'banquanFw()\'>");
document.writeln("	<i></i>");
document.writeln("	<p>版权服务<span>COPYRIGHT</span></p>");
document.writeln("	<b class=\'jiant\'></b>");
document.writeln("</div>");
document.writeln("<div class=\'childMenu childMenu_a\'>");
document.writeln("	<div class=\'div_asd niup\'> ");
document.writeln("		<div class=\'ZheShiK\'>");
document.writeln("			<div class=\'\'>  ");
document.writeln("				<ul>                              ");
document.writeln("					<li><h3 class=\'biaot banq1\'>软件著作</h3></li>");
document.writeln("					<li><a href=\'#\'>小程序</a></li>");
document.writeln("					<li><a href=\'#\'>手机APP</a></li>");
document.writeln("					<li><a href=\'#\'>网站</a></li>");
document.writeln("					<li><a href=\'#\'>电脑软件</a></li> ");
document.writeln("				</ul> ");
document.writeln("			</div>         ");
document.writeln("		</div>");
document.writeln("		<div class=\'LiangGe_FD\'></div>");
document.writeln("	</div> ");
document.writeln("	<div class=\'div_asd niup\'> ");
document.writeln("		<div class=\'ZheShiK\'>");
document.writeln("			<div class=\'\'>  ");
document.writeln("				<ul>                              ");
document.writeln("					<li><h3 class=\'biaot banq2\'>音乐作品</h3></li>");
document.writeln("					<li><a href=\'#\'>曲艺作品</a></li>");
document.writeln("					<li><a href=\'#\'>原创歌曲</a></li>");
document.writeln("					<li><a href=\'#\'>音乐</a></li>");
document.writeln("					<li><a href=\'#\'>铃声</a></li> ");
document.writeln("					<li><a href=\'#\'>曲谱</a></li> ");
document.writeln("				</ul> ");
document.writeln("			</div> ");
document.writeln("		</div>");
document.writeln("		<div class=\'LiangGe_FD\'></div>");
document.writeln("	</div>");
document.writeln("	<div class=\'div_asd niup\'> ");
document.writeln("		<div class=\'ZheShiK\'>");
document.writeln("			<div class=\'\'>  ");
document.writeln("				<ul>                              ");
document.writeln("					<li><h3 class=\'biaot banq3\'>影视作品</h3></li>");
document.writeln("					<li><a href=\'#\'>电影</a></li>");
document.writeln("					<li><a href=\'#\'>微电影</a></li>");
document.writeln("					<li><a href=\'#\'>电视剧</a></li>");
document.writeln("					<li><a href=\'#\'>动画片</a></li> ");
document.writeln("					<li><a href=\'#\'>广告片</a></li> ");
document.writeln("					<li><a href=\'#\'>宣传片</a></li> ");
document.writeln("					<li><a href=\'#\'>综艺节目</a></li> ");
document.writeln("					<li><a href=\'#\'>多媒体作品</a></li> ");
document.writeln("				</ul> ");
document.writeln("			</div> ");
document.writeln("		</div>");
document.writeln("		<div class=\'LiangGe_FD\'></div>");
document.writeln("	</div>");
document.writeln("	<div class=\'div_asd niup\'> ");
document.writeln("		<div class=\'ZheShiK\'>");
document.writeln("			<div class=\'\'>  ");
document.writeln("				<ul>                              ");
document.writeln("					<li><h3 class=\'biaot banq4\'>摄影作品</h3></li>");
document.writeln("					<li><a href=\'#\'>拍摄照片</a></li>");
document.writeln("					<li><a href=\'#\'>个人写真</a></li> ");
document.writeln("				</ul> ");
document.writeln("			</div> ");
document.writeln("		</div>");
document.writeln("		<div class=\'LiangGe_FD\'></div>");
document.writeln("	</div>");
document.writeln("	<div class=\'div_asd niup\'> ");
document.writeln("		<div class=\'ZheShiK\'>            ");
document.writeln("			<div class=\'\'>  ");
document.writeln("				<ul>                              ");
document.writeln("					<li><h3 class=\'biaot banq5\'>文字作品</h3></li>");
document.writeln("					<li><a href=\'#\'>书籍</a></li>");
document.writeln("					<li><a href=\'#\'>广告语</a></li>");
document.writeln("					<li><a href=\'#\'>小品|话剧剧本</a></li>");
document.writeln("					<li><a href=\'#\'>商业计划书</a></li> ");
document.writeln("					<li><a href=\'#\'>学术论文</a></li> ");
document.writeln("					<li><a href=\'#\'>诗词歌赋</a></li> ");
document.writeln("				</ul> ");
document.writeln("			</div> ");
document.writeln("		</div>");
document.writeln("		<div class=\'LiangGe_FD\'></div>");
document.writeln("	</div>");
document.writeln("	<div class=\'div_asd niup\'> ");
document.writeln("		<div class=\'ZheShiK\'>");
document.writeln("			<div class=\'\'>  ");
document.writeln("				<ul>                        ");
document.writeln("					<li><h3 class=\'biaot banq6\'>美术作品</h3></li>");
document.writeln("					<li><a href=\'#\'>logo</a></li>");
document.writeln("					<li><a href=\'#\'>门头</a></li>");
document.writeln("					<li><a href=\'#\'>VI体系</a></li>");
document.writeln("					<li><a href=\'#\'>包装平面图</a></li> ");
document.writeln("					<li><a href=\'#\'>广告版面</a></li> ");
document.writeln("					<li><a href=\'#\'>网页版面</a></li> ");
document.writeln("				</ul> ");
document.writeln("			</div> ");
document.writeln("		</div>");
document.writeln("		<div class=\'LiangGe_FD\'></div>");
document.writeln("	</div>");
document.writeln("	<div class=\'div_asd niup\'> ");
document.writeln("		<div class=\'ZheShiK\'>");
document.writeln("			<div class=\'\'>  ");
document.writeln("				<ul>");
document.writeln("					<li><h3 class=\'biaot banq7\'>相关服务</h3></li>");
document.writeln("					<li><a href=\'banquanFw_BianH.html\'>版权变更</a></li>");
document.writeln("					<li><a href=\'#\'>版权转让</a></li>");
document.writeln("					<li><a href=\'#\'>版权补证</a></li>");
document.writeln("					<li><a href=\'#\'>版权许可</a></li> ");
document.writeln("					<li><a href=\'#\'>版权注销</a></li> ");
document.writeln("				</ul> ");
document.writeln("			</div> ");
document.writeln("		</div>");
document.writeln("		<div class=\'LiangGe_FD\'></div>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("</li>");
document.writeln("<li class=\'nisd_w1\'>");
document.writeln("<div class=\'left\' onclick=\'tiaomaFw()\'>");
document.writeln("	<i></i>");
document.writeln("	<p>条码服务<span>BARCODE</span></p>");
document.writeln("	<b class=\'jiant\'></b>");
document.writeln("</div>");
document.writeln("<div class=\'childMenu childMenu_b\'>  ");
document.writeln("	<div class=\'div_asd\'> ");
document.writeln("		<div class=\'ZheShiK\'>");
document.writeln("			<div class=\'\'> ");
document.writeln("				<h3 class=\'biaot jiaoyi\'>条码新办</h3>");
document.writeln("				<ul>");
document.writeln("					<li class=\'hot\'><a href=\'#\'>条码新申请</a></li>");
document.writeln("					<li><a href=\'#\'>条码续展</a></li>");
document.writeln("					<li><a href=\'#\'>胶片新增 </a></li>");
document.writeln("					<li><a href=\'#\'>条码变更</a></li>");
document.writeln("					<li><a href=\'#\'>条码维护</a></li>");
document.writeln("					<li class=\'color_hot\'><a href=\'#\'>二维码申请</a></li> ");
document.writeln("				</ul> ");
document.writeln("			</div> ");
document.writeln("		</div>");
document.writeln("		<!-- <div class=\'LiangGe_FD\'></div> -->");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("</li>");
document.writeln("<li class=\'nisd_w2\'>");
document.writeln("<div class=\'left\' onclick=\' qiyeFw()\'> ");
document.writeln("	<i></i>");
document.writeln("	<p>企业服务<span>ENTERPRISE</span></p>");
document.writeln("	<b class=\'jiant\'></b>");
document.writeln("</div>");
document.writeln("<div class=\'childMenu childMenu_c\'>  ");
document.writeln("	<div class=\'div_asd\'> ");
document.writeln("		<div class=\'ZheShiK\'>");
document.writeln("			<div class=\'\'> ");
document.writeln("				<h3 class=\'biaot jinpai\'>工商服务</h3>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\'#\'>公司注册</a></li>");
document.writeln("					<li><a href=\'#\'>公司变更</a></li>");
document.writeln("					<li><a href=\'#\'>公司注销</a></li>");
document.writeln("					<li><a href=\'#\'>公司转让</a></li>");
document.writeln("					<li><a href=\'#\'>食品流通许可证办理</a></li>");
document.writeln("					<li><a href=\'#\'>个体户执照登记</a></li> ");
document.writeln("				</ul> ");
document.writeln("			</div> ");
document.writeln("		</div>");
document.writeln("		<div class=\'LiangGe_FD\'></div>");
document.writeln("	</div>               ");
document.writeln("	<div class=\'div_asd\'> ");
document.writeln("		<div class=\'ZheShiK\'>");
document.writeln("			<div class=\'\'> ");
document.writeln("				<h3 class=\'biaot huangg\'>设计服务</h3>");
document.writeln("				<ul>");
document.writeln("					<li class=\'hot\'><a href=\'#\'>logo设计</a></li>");
document.writeln("					<li><a href=\'#\'>VI设计</a></li>");
document.writeln("					<li><a href=\'#\'>网页设计</a></li>");
document.writeln("					<li><a href=\'#\'>电商店面设计</a></li>");
document.writeln("					<li><a href=\'#\'>广告设计</a></li>");
document.writeln("					<li><a href=\'#\'>宣传册设计</a></li> ");
document.writeln("					<li><a href=\'#\'>产品包装设计</a></li> ");
document.writeln("					<li><a href=\'#\'>卡通人物设计</a></li> ");
document.writeln("					<li><a href=\'#\'>吉祥物设计</a></li> ");
document.writeln("				</ul> ");
document.writeln("			</div> ");
document.writeln("		</div>");
document.writeln("		<div class=\'LiangGe_FD\'></div>");
document.writeln("	</div>");
document.writeln("	<div class=\'div_asd\'> ");
document.writeln("		<div class=\'ZheShiK\'>        ");
document.writeln("			<div class=\'\'> ");
document.writeln("				<h3 class=\'biaot guoji\'>认证评估服务</h3>");
document.writeln("				<ul>");
document.writeln("					<li class=\'hot\'><a href=\'#\'>高新技术企业</a></li>");
document.writeln("					<li><a href=\'#\'>ISO系列认证</a></li>");
document.writeln("					<li><a href=\'#\'>地理标志产品（质监）</a></li>");
document.writeln("					<li><a href=\'#\'>名牌产品认定</a></li>");
document.writeln("					<li><a href=\'#\'>守合同·重信用</a></li>");
document.writeln("					<li class=\'color_hot\'><a href=\'#\'>商标价值评估</a></li>");
document.writeln("					<li class=\'color_hot\'><a href=\'#\'>专利技术评估</a></li> ");
document.writeln("				</ul> ");
document.writeln("			</div> ");
document.writeln("		</div>");
document.writeln("		<div class=\'LiangGe_FD\'></div>");
document.writeln("	</div>");
document.writeln("	<div class=\'div_asd\'> ");
document.writeln("		<div class=\'ZheShiK\'>");
document.writeln("			<div class=\'\'> ");
document.writeln("				<h3 class=\'biaot huangg\'>互联网服务</h3>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\'#\'>域名注册</a></li>");
document.writeln("					<li><a href=\'#\'>网站建设</a></li>");
document.writeln("					<li><a href=\'#\'>公司注销</a></li>");
document.writeln("					<li><a href=\'#\'>公司转让</a></li>");
document.writeln("					<li><a href=\'#\'>食品流通许可证办理</a></li>");
document.writeln("					<li><a href=\'#\'>个体户执照登记</a></li> ");
document.writeln("				</ul> ");
document.writeln("			</div> ");
document.writeln("		</div>");
document.writeln("		<div class=\'LiangGe_FD\'></div>");
document.writeln("	</div>");
document.writeln("		</div>");
document.writeln("	</li>	");
document.writeln("</ul>");